### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by blakejoy** [youyanggu/groupme_stats#29]
Trying to pull Direct messages of count 29000 and I get list index out of range when running retrieve_msgs.py token -d -a. I can't use the persons direct name since it contains an emoji.

**Comment by youyanggu** [comment]
Do you mind providing the full error? A screenshot would work. Thanks.

**Comment by blakejoy** [comment]
![image](https://user-images.githubusercontent.com/9423898/28423663-aaa7e1fa-6d39-11e7-95b4-6fde5756db0c.png)

**Comment by youyanggu** [comment]
Do a 'git pull' and try again. I believe it should be fixed.

**Comment by blakejoy** [comment]
I was able to pull a majority of the messages. Still missing like 4000 more. You think its a paging thing with groupme chats?

**Comment by youyanggu** [comment]
Not sure why you're short, but that seems to be all GroupMe is returning.
